// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(s) {
  var uppercase = s.toUpperCase();
  var malformedMethodError_payload = {
    err: "unknown-method",
    msg: "Unknown method: " + uppercase + "",
    details: "{}"
  };
  var malformedMethodError = {
    status: 405,
    payload: malformedMethodError_payload
  };
  switch (uppercase) {
    case "DELETE" :
        return {
                TAG: /* Ok */0,
                _0: /* DELETE */4
              };
    case "GET" :
        return {
                TAG: /* Ok */0,
                _0: /* GET */0
              };
    case "PATCH" :
        return {
                TAG: /* Ok */0,
                _0: /* PATCH */3
              };
    case "POST" :
        return {
                TAG: /* Ok */0,
                _0: /* POST */2
              };
    case "PUT" :
        return {
                TAG: /* Ok */0,
                _0: /* PUT */1
              };
    default:
      return {
              TAG: /* Error */1,
              _0: malformedMethodError
            };
  }
}

function toString(t) {
  switch (t) {
    case /* GET */0 :
        return "GET";
    case /* PUT */1 :
        return "PUT";
    case /* POST */2 :
        return "POST";
    case /* PATCH */3 :
        return "PATCH";
    case /* DELETE */4 :
        return "DELETE";
    
  }
}

exports.make = make;
exports.toString = toString;
/* No side effect */
