// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Route$BApi = require("./Route.bs.js");
var Belt_MapString = require("rescript/lib/js/belt_MapString.js");

function make(param) {
  
}

function route(t, route$1, method, handler) {
  return Belt_MapString.set(t, Route$BApi.toString(route$1), {
              route: route$1,
              method: method,
              handler: handler
            });
}

exports.make = make;
exports.route = route;
/* No side effect */
