// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");

function serve(port, host) {
  return Http.createServer(function (request, response) {
                var method = request.method;
                var url = request.url;
                console.log("Incoming " + method + " request from URL " + url + "");
                response.writeHead(200, {
                        "x-powered-by": "BApi",
                        "content-type": "application/json"
                      }).end(Buffer.from(JSON.stringify({
                              msg: "Hello, world"
                            })));
              }).listen(port, host, (function (param) {
                console.log("starting BApi server");
              }));
}

var Server = {
  serve: serve
};

serve(8000, "127.0.0.1");

exports.Server = Server;
/*  Not a pure module */
